apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multicontainers-pod
  name: multicontainers-pod
spec:
  containers:
  - image: httpd
    name: httpd-pod
  - image: alpine
    name: debug
    command: 
      - "sleep"
      - "99999999999"
